@startuml
'https://plantuml.com/class-diagram

title Simple Factory Design Pattern

abstract class AbstractTV {
    turn_on()
    turn_off()
}

class TVFactory {
    tv_sets:dict[str:class]
    create_instance(tv_brand)
    load_tvs()
}

class LGTV {
    turn_on()
    turn_off()
}

class PhillipsTV {
    turn_on()
    turn_off()
}

note left of TVFactory: Create and return\nproduct instance
note right of AbstractTV: Abstract class.\nStipulates the methods\nto be implemented
note "Concrete classes" as N1

LGTV .up.|> AbstractTV
PhillipsTV .up.|> AbstractTV
TVFactory .right.|> AbstractTV
PhillipsTV .. N1
LGTV .. N1

@enduml